iterm2:
  theme: ayu
tmux:
  theme: inherit
nvim:
  theme: inherit
  bufferline: on
  statusline: on
  gitgutter: on
  dynamic-darkmode: on
  icons:
    diagnostic:
      error: 
      warn: 
      info: 
      hint: ﯧ
    gitgutter:
      added: ▌
      modified: ▌
      removed: ▸
